#!/usr/bin/env python

from ConfigParser import ConfigParser
from lxml import etree
import sys
from ymp.repos import *


NS = 'http://opensuse.org/Standards/One_Click_Install'

def make_path(start, *components):
    pathstr = start
    for c in components:
        pathstr += '/{%s}%s' % (NS, c)
    return pathstr

def make_finder(start, *components):
    return etree.ETXPath(start, components)

def parse_entry(elem):
    return dict([ (child.tag[len(NS)+2:], child.text) for child in elem ])

def parse_ymp_file(fname):
    with file(fname, 'r') as f:
        tree = etree.parse(f)
        find_repos = etree.ETXPath(
            '/{%s}metapackage/{%s}group/{%s}repositories/{%s}repository' \
                % ((NS,)*4))
        repos = find_repos(tree)
        find_software = etree.ETXPath(
            '/{%s}metapackage/{%s}group/{%s}software/{%s}item' \
                % ((NS,)*4))
        software_items = find_software(tree)

        try:
            for repo in repos:
            
                metadata = parse_entry(repo)
                metadata['recommended'] = True if (repo.get('recommended') == 'true') else False
                print metadata
                print "--------"

                repo_obj = YumRepository(metadata)
                print repo_obj
                #repo_obj.persist()
                print "--------"
            for item in software_items:
                metadata = parse_entry(item)
                print metadata['name']

        except IOError:
            print >>sys.stderr, "No permission to create repository descriptor"


if __name__ == '__main__':
    if len(sys.argv) != 2:
        print >>sys.stderr, "Usage: ympcli metapackage.ymp"
        sys.exit(1)

    parse_ymp_file(sys.argv[1])

        
