#! /usr/bin/env python
# encoding: utf-8
# Michel Alexandre Salim, 2012
# based on sample Vala multi-file wscript by Joshua Simmons 2010

bld.program(
	packages = ['gtk+-3.0', 'libxml-2.0'],
	target   = 'ymp-install',
	uselib   = ['GLIB', 'GTK', 'XML'],
	source   = 'main.vala'
	)

